language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: qCt2WBSejLgzRwxcClUpi6ipYUbFa6p1AaUT22qG9zWGelY/4Pwbm1XjJkn7NdxHtc6k0tZoCEebG4Flw/QiUMmFL8jPb0XOBjpdVzFUcLMZ76sL+mYf/furnht396jxatJbjR8gKqmZOk3LjjuNPNoj/z7+GN0AhjYzxutUhmA=
