language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: iqb9Dq06pGIHNrg3PbZ0QF4RWzs010kNfkv7OX+n0G4uBSs3wqkyXwmHnVL7yh5rC2GmH1S8ab/JE7mdkx9VWT9fqFuhJiaWF3DBKl8CiV+9mD+/VynlzU+DIg/o5An9MO9O18dy53Lt1Xuy8a7siCG1CkgroCtMWZh+n2agZqw=
